name: dpgsql 
description: High Performance PostgreSQL Driver for Dart 
version: 1.0.1
homepage: 
repository: https://github.com/insinfo/dpgsql

environment:
  sdk: ^3.6.0
    
dependencies:
  # No external runtime dependencies.

dev_dependencies:
  test: any

